const { spawn } = require('child_process');
const express = require('express');
const pool = require('../config/db');
const authMiddleware = require('../middleware/auth'); // Protects this route

const router = express.Router();

// ==========================================
// 1. UPLOAD NEW WASTE LISTING (Protected)
// ==========================================
router.post('/upload', authMiddleware, async (req, res) => {
    const { title, material_type, quantity, unit, description, keywords } = req.body;

    try {
        // req.user.id is automatically populated by our authMiddleware token check
        const generator_id = req.user.id;

        const newListing = await pool.query(
            `INSERT INTO waste_listings (generator_id, title, material_type, quantity, unit, description, keywords)
             VALUES ($1, $2, $3, $4, $5, $6, $7) 
             RETURNING *`,
            [generator_id, title, material_type, quantity, unit, description, keywords || []]
        );

        res.status(201).json({
            message: "Industrial waste resource listed successfully.",
            listing: newListing.rows[0]
        });
    } catch (err) {
        console.error(err.message);
        res.status(500).json({ error: "Failed to publish waste listing on server." });
    }
});

// ==========================================
// 2. GET ALL AVAILABLE WASTE LISTINGS (Public/Searchable)
// ==========================================
router.get('/all', async (req, res) => {
    try {
        // Fetch listings and join with industry details to show location info
        const listings = await pool.query(
            `SELECT wl.*, i.company_name, i.district, i.state, i.industry_type 
             FROM waste_listings wl
             JOIN industries i ON wl.generator_id = i.id
             WHERE wl.is_available = TRUE
             ORDER BY wl.created_at DESC`
        );

        res.json(listings.rows);
    } catch (err) {
        console.error(err.message);
        res.status(500).json({ error: "Failed to retrieve waste repository." });
    }
});
// ==========================================
// 3. SEARCH & FILTER WASTE (By District/Material Type)
// ==========================================
router.get('/search', async (req, res) => {
    // Expect query parameters like /api/waste/search?district=Ernakulam&material_type=Wood Mills
    const { district, material_type } = req.query;

    try {
        let queryText = `
            SELECT wl.*, i.company_name, i.district, i.state 
            FROM waste_listings wl
            JOIN industries i ON wl.generator_id = i.id
            WHERE wl.is_available = TRUE
        `;
        const queryParams = [];

        // Dynamically add filters if the frontend requests them
        if (district) {
            queryParams.push(district);
            queryText += ` AND i.district = $${queryParams.length}`;
        }
        if (material_type) {
            queryParams.push(material_type);
            queryText += ` AND wl.material_type = $${queryParams.length}`;
        }

        queryText += ` ORDER BY wl.created_at DESC`;

        const filteredListings = await pool.query(queryText, queryParams);
        res.json(filteredListings.rows);
    } catch (err) {
        console.error(err.message);
        res.status(500).json({ error: "Search query failed on server." });
    }
});
// ==========================================
// 4. SMART MATCHING ENGINE ENDPOINT (Protected)
// ==========================================
router.get('/smart-matches', authMiddleware, async (req, res) => {
    try {
        // 1. Fetch the logged-in company's material needs profile
        const buyerResult = await pool.query(
            'SELECT id, industry_type, raw_material_keywords FROM industries WHERE id = $1',
            [req.user.id]
        );
        
        if (buyerResult.rows.length === 0) {
            return res.status(404).json({ error: "Industry profile not found." });
        }
        const targetIndustry = buyerResult.rows[0];

        // 2. Fetch all available waste listings generated by *other* companies
        const listingsResult = await pool.query(
            `SELECT wl.*, i.company_name, i.district, i.state, i.industry_type 
             FROM waste_listings wl
             JOIN industries i ON wl.generator_id = i.id
             WHERE wl.is_available = TRUE AND wl.generator_id != $1`,
            [req.user.id]
        );
        const availableListings = listingsResult.rows;

        // 3. Spawn the Python subprocess execution bridge
        // Note: Change 'python' to 'python3' if your environment path specifically uses python3
        const pythonProcess = spawn('python', ['./engine/matcher.py']);

        let pythonData = "";
        let pythonError = "";

        // Send data directly to the Python script via stdin stream
        pythonProcess.stdin.write(JSON.stringify({
            target_industry: targetIndustry,
            listings: availableListings
        }));
        pythonProcess.stdin.end();

        // Capture output from Python stdout stream
        pythonProcess.stdout.on('data', (data) => {
            pythonData += data.toString();
        });

        // Capture runtime execution tracking errors from Python stderr stream
        pythonProcess.stderr.on('data', (data) => {
            pythonError += data.toString();
        });

        // Process finishes executing
        pythonProcess.on('close', (code) => {
            if (code !== 0 || pythonError) {
                console.error(`Python script engine failure. Exit code: ${code}. Error: ${pythonError}`);
                return res.status(500).json({ error: "AI matching engine calculations crashed." });
            }

            try {
                const recommendations = JSON.parse(pythonData);
                res.json(recommendations);
            } catch (parseErr) {
                console.error("Failed parsing Python output payload:", parseErr);
                res.status(500).json({ error: "Invalid payload format received from analytics engine." });
            }
        });

    } catch (err) {
        console.error(err.message);
        res.status(500).json({ error: "Internal server bottleneck handling smart matches." });
    }
});
module.exports = router;